#!/usr/bin/env bash
# orbweaver setup wizard
# Generates docker/.env and optionally starts the stack.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/docker/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker/docker-compose.yml"

# ── colours ──────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    BOLD="\033[1m"
    GREEN="\033[0;32m"
    CYAN="\033[0;36m"
    RESET="\033[0m"
else
    BOLD="" GREEN="" CYAN="" RESET=""
fi

echo -e "${BOLD}orbweaver setup${RESET}"
echo "─────────────────────────────────────────"

# ── prereq check ─────────────────────────────────────────────────────────────
for cmd in docker; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "Error: '$cmd' is not installed." >&2
        exit 1
    fi
done

if ! docker compose version &>/dev/null; then
    echo "Error: 'docker compose' (v2) is not available." >&2
    exit 1
fi

# ── prompt helper ─────────────────────────────────────────────────────────────
ask() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local answer

    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${CYAN}${prompt}${RESET} [${default}]: ")" answer
        echo "${answer:-$default}"
    else
        while true; do
            read -rp "$(echo -e "${CYAN}${prompt}${RESET}: ")" answer
            if [[ -n "$answer" ]]; then
                echo "$answer"
                break
            fi
            echo "  (required — please enter a value)" >&2
        done
    fi
}

echo ""
echo -e "${BOLD}Diode connection${RESET}"
DIODE_HOST=$(ask "Diode host (IP or hostname)" "" "")
DIODE_PORT=$(ask "Diode gRPC port" "8080" "")
DIODE_CLIENT_ID=$(ask "Diode client ID" "diode-ingest" "")
DIODE_CLIENT_SECRET=$(ask "Diode client secret" "" "")

echo ""
echo -e "${BOLD}NetBox API${RESET}"
NETBOX_HOST=$(ask "NetBox host (IP or hostname)" "$DIODE_HOST" "")
NETBOX_PORT=$(ask "NetBox HTTP port" "8000" "")
NETBOX_TOKEN=$(ask "NetBox API token" "" "")

echo ""
echo -e "${BOLD}orbweaver${RESET}"
ORBWEAVER_HOST=$(ask "orbweaver host — IP/hostname the browser can reach" "$DIODE_HOST" "")

echo ""
echo -e "${BOLD}SSH config (optional)${RESET}"
SSH_CONFIG_DEFAULT="../../orb/ssh-napalm.conf"
SSH_CONFIG_INPUT=$(ask "SSH config path (leave default if unsure)" "$SSH_CONFIG_DEFAULT" "")

# ── write .env ────────────────────────────────────────────────────────────────
mkdir -p "$SCRIPT_DIR/docker"

cat > "$ENV_FILE" <<EOF
# orbweaver environment — generated by setup.sh
# Edit manually or re-run ./setup.sh to change values.

# ── Diode connection ──────────────────────────────────────────────────────────
DIODE_HOST=${DIODE_HOST}
DIODE_PORT=${DIODE_PORT}
DIODE_CLIENT_ID=${DIODE_CLIENT_ID}
DIODE_CLIENT_SECRET=${DIODE_CLIENT_SECRET}

# ── NetBox API ────────────────────────────────────────────────────────────────
NETBOX_HOST=${NETBOX_HOST}
NETBOX_PORT=${NETBOX_PORT}
NETBOX_TOKEN=${NETBOX_TOKEN}

# ── orbweaver host ────────────────────────────────────────────────────────────
ORBWEAVER_HOST=${ORBWEAVER_HOST}

# ── SSH config ────────────────────────────────────────────────────────────────
SSH_CONFIG=${SSH_CONFIG_INPUT}

# ── Cleanup script ────────────────────────────────────────────────────────────
CLEANUP_TAG=discovered
EOF

echo ""
echo -e "${GREEN}✓ docker/.env written${RESET}"

# ── optionally start stack ────────────────────────────────────────────────────
echo ""
read -rp "$(echo -e "Pull images and start the stack? [Y/n]: ")" START_ANSWER
START_ANSWER="${START_ANSWER:-Y}"

if [[ "$START_ANSWER" =~ ^[Yy] ]]; then
    echo ""
    echo "Pulling images…"
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" pull

    echo "Starting stack…"
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

    echo ""
    echo -e "${GREEN}✓ Stack started${RESET}"
    echo ""
    echo -e "  Frontend:  ${BOLD}http://${ORBWEAVER_HOST}:3000${RESET}"
    echo -e "  Backend:   ${BOLD}http://${ORBWEAVER_HOST}:8072/api/v1/status${RESET}"
    echo ""
else
    echo ""
    echo "To start later:"
    echo "  docker compose -f docker/docker-compose.yml --env-file docker/.env up -d"
    echo ""
fi
