#!/usr/bin/env bash
# orbweaver setup wizard
# Generates a self-contained docker-compose.yml with all values baked in.
# No .env file is needed on the target host — copy just the generated file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="$SCRIPT_DIR/orbweaver-compose.yml"

# ── colours ──────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    BOLD="\033[1m"
    GREEN="\033[0;32m"
    CYAN="\033[0;36m"
    RESET="\033[0m"
else
    BOLD="" GREEN="" CYAN="" RESET=""
fi

echo -e "${BOLD}orbweaver setup${RESET}"
echo "─────────────────────────────────────────"

# ── prereq check ─────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
    echo "Error: 'docker' is not installed." >&2
    exit 1
fi
if ! docker compose version &>/dev/null; then
    echo "Error: 'docker compose' (v2) is not available." >&2
    exit 1
fi

# ── prompt helper ─────────────────────────────────────────────────────────────
ask() {
    local prompt="$1"
    local default="$2"
    local answer

    if [[ -n "$default" ]]; then
        read -rp "$(echo -e "${CYAN}${prompt}${RESET} [${default}]: ")" answer
        echo "${answer:-$default}"
    else
        while true; do
            read -rp "$(echo -e "${CYAN}${prompt}${RESET}: ")" answer
            if [[ -n "$answer" ]]; then
                echo "$answer"
                break
            fi
            echo "  (required — please enter a value)" >&2
        done
    fi
}

echo ""
echo -e "${BOLD}Diode connection${RESET}"
DIODE_HOST=$(ask "Diode host (IP or hostname)" "")
DIODE_PORT=$(ask "Diode gRPC port" "8080")
DIODE_CLIENT_ID=$(ask "Diode client ID" "diode-ingest")
DIODE_CLIENT_SECRET=$(ask "Diode client secret" "")

echo ""
echo -e "${BOLD}NetBox API${RESET}"
NETBOX_HOST=$(ask "NetBox host (IP or hostname)" "$DIODE_HOST")
NETBOX_PORT=$(ask "NetBox HTTP port" "8000")
NETBOX_TOKEN=$(ask "NetBox API token" "")

echo ""
echo -e "${BOLD}orbweaver${RESET}"
ORBWEAVER_HOST=$(ask "orbweaver host — IP/hostname the browser can reach" "$DIODE_HOST")

echo ""
echo -e "${BOLD}SSH config (optional)${RESET}"
SSH_CONFIG=$(ask "Path to ssh-napalm.conf on this host" "/opt/orb/ssh-napalm.conf")

# ── write self-contained compose file ────────────────────────────────────────
cat > "$OUT_FILE" <<EOF
# orbweaver — generated by setup.sh
# Deploy: docker compose -f orbweaver-compose.yml up -d
# Stop:   docker compose -f orbweaver-compose.yml down

name: orbweaver

services:
  orbweaver:
    image: ghcr.io/triomat/orbweaver-backend:latest
    ports:
      - "8072:8072"
    command: >
      orbweaver
        --host 0.0.0.0
        --port 8072
        --diode-target grpc://${DIODE_HOST}:${DIODE_PORT}/diode
        --diode-client-id ${DIODE_CLIENT_ID}
        --diode-client-secret ${DIODE_CLIENT_SECRET}
    environment:
      - ORBWEAVER_REVIEW_DIR=/reviews
      - ORBWEAVER_CORS_ORIGINS=*
    volumes:
      - orbweaver-reviews:/reviews
      - ${SSH_CONFIG}:/opt/orb/ssh-napalm.conf:ro
    restart: unless-stopped

  frontend:
    image: ghcr.io/triomat/orbweaver-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://${ORBWEAVER_HOST}:8072
    depends_on:
      - orbweaver
    restart: unless-stopped

volumes:
  orbweaver-reviews:
    driver: local
EOF

echo ""
echo -e "${GREEN}✓ ${OUT_FILE} written${RESET}"
echo ""
echo "  Copy this file to any host with Docker and run:"
echo -e "    ${BOLD}docker compose -f orbweaver-compose.yml up -d${RESET}"
echo ""

# ── optionally start here ─────────────────────────────────────────────────────
read -rp "$(echo -e "Pull images and start the stack on this host now? [Y/n]: ")" START_ANSWER
START_ANSWER="${START_ANSWER:-Y}"

if [[ "$START_ANSWER" =~ ^[Yy] ]]; then
    echo ""
    echo "Pulling images…"
    docker compose -f "$OUT_FILE" pull

    echo "Starting stack…"
    docker compose -f "$OUT_FILE" up -d

    echo ""
    echo -e "${GREEN}✓ Stack started${RESET}"
    echo ""
    echo -e "  Frontend:  ${BOLD}http://${ORBWEAVER_HOST}:3000${RESET}"
    echo -e "  Backend:   ${BOLD}http://${ORBWEAVER_HOST}:8072/api/v1/status${RESET}"
    echo ""
fi
